doctor/urls.py
from django.conf.urls import url
from doctor.paymen_views import DoctorRegisterPayment, SponsorPayment, UserMeetPayment
from doctor.views import BaseIndexView, DashboardView, Test, DoctorFormsView, \
    DoctorBlogDetailView, DoctorTvView, SendMail, DoctorBaseSearchView, \
    ChangeProfilePicture,  MeetDoctorTestView, DashboradEducation, \
    DashboradWork, DashboradNealiyyet, ChangeProfilePictureOne, ChangeProfilePictureTwo, \
    DashboardMeetDateView, DoctorRegisterPaymentSuccess, DoctorDetailTestView, \
    SposorMoneyView, DoctorAddBlog, DoctorBlogList, MeetingDoneView, PasiendListView, \
    AddReview,StaticPageView
from .views import doctor_comment_ajax, doctor_meeting_accept

urlpatterns = [
    url(r'^$', BaseIndexView.as_view(), name="index"),
    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard"),
    # url(r'^', include("news.urls")),
    # base settings page
    url(r'^dashboard/education/$', DashboradEducation.as_view(), name="dashboard-education"),
    url(r'^dashboard/work_experience/$', DashboradWork.as_view(), name="dashboard-work"),
    url(r'^dashboard/activities/$', DashboradNealiyyet.as_view(), name="dashboard-activity"),
    url(r'^dashboard/personal-info/$', DashboardView.as_view(), name="dashboard-personal"),
    url(r'^dashboard/meet-date/$', DashboardMeetDateView.as_view(), name="dashboard-meet-date"),
    url(r'^dashboard/payment/$', DoctorRegisterPaymentSuccess.as_view(), name="dashboard-payment-success"),
    url(r'^dashboard/sponsored/$', SposorMoneyView.as_view(), name="dashboard-sponsor"),
    url(r'^dashboard/pasients/$', PasiendListView.as_view(), name="dashboard-pasient"),
    url(r'^dashboard/pasient/accept/(?P<m_id>[0-9]+)/(?P<a_slug>[-\w]+)/$', doctor_meeting_accept, name="doctor_meeting_accept"),
    url(r'^dashboard/add_review/$', AddReview.as_view(), name="add-review"),

    url(r'^testing/$', Test.as_view(), name="test"),
    url(r'^forms/$', DoctorFormsView.as_view(), name="doctor-blog"),
    url(r'^ajax/comment-ajax/(?P<id>[-\w]+)/dsdsds/$', doctor_comment_ajax, name="doctor_comment_ajax"),
    url(r'^tv/$', DoctorTvView.as_view(), name="doctor-tv"),
    url(r'^blog/(?P<slug>[-\w]+)/$', DoctorBlogDetailView.as_view(), name="doctor-blog"),
    url(r'^sendmail/$', SendMail.as_view(), name="send-mail"),
    url(r'^search/$', DoctorBaseSearchView.as_view(), name="search"),
    url(r'^doctor/(?P<slug>[-\w]+)/$', DoctorDetailTestView.as_view(), name="doctor-detail"),
    url(r'^page/(?P<slug>[\w-]+)/$', StaticPageView.as_view(), name="custom-page"),
    url(r'^doctor/add/blog/$', DoctorAddBlog.as_view(), name="doctor-add-blog"),
    url(r'^doctor/list/blog/$', DoctorBlogList.as_view(), name="doctor-blog-list"),
    url(r'^meet/doctor/$', MeetDoctorTestView.as_view(), name="doctor-meet"),
    url(r'^meet/done/$', MeetingDoneView.as_view(), name="doctor-meeting-done"),
    url(r'^picture/upload/$', ChangeProfilePicture.as_view(), name="upload-picture"),
    url(r'^picture/upload/one/$', ChangeProfilePictureOne.as_view(), name="upload-picture1"),
    url(r'^picture/upload/two/$', ChangeProfilePictureTwo.as_view(), name="upload-picture2"),


    # Odenishlerin url tehlukesiz
    url(r'^user/meeting/payment/$', UserMeetPayment.as_view(), name="pay-user-meet"),
    url(r'^doctor/registration/payment/$', DoctorRegisterPayment.as_view(), name="pay-doctor-register"),
    url(r'^doctor/sponsored/payment/$', SponsorPayment.as_view(), name="pay-doctor-sponsored"),

]

tezsagal_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils import translation
from django.views import generic
from doctor.paymen_views import BasePaymentCheckView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^payments/', BasePaymentCheckView.as_view(), name='payment-check'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^e8b138ed91cf.html$', generic.TemplateView.as_view(template_name='e8b138ed91cf.html'), name='site-verification-com'),
    url(r'^e6e7c523116a.html$', generic.TemplateView.as_view(template_name='e6e7c523116a.html'), name='site-verification-az'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
    url(r'^', include("doctor.urls", namespace="base")),
    url(r'^pages/', include('django.contrib.flatpages.urls'), name='flat'),
    url(r'^account/', include("base_user.urls", namespace="account")),
)

doctor/forms.py
from django import forms
from doctor.models import ContactMessages, DoctorBlog
from PIL import Image
from geoposition.forms import GeopositionField

VALID_IMAGE_FILETYPES = (
    '.jpg','.png','.tiff'
)

class LeaveMessageForm(forms.ModelForm):
    class Meta:
        model = ContactMessages
        fields = ('name', 'phone', 'message')


class DashboardPersonalForm(forms.Form):
    base_name = forms.CharField(max_length=255)
    personal_info = forms.Textarea()

class BlogAddForm(forms.ModelForm):
    class Meta:
        model = DoctorBlog
        fields = ('author','title', 'image', 'text')

    def __init__(self, *args, **kwargs):
        super(BlogAddForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True


class PositionForm(forms.Form):
    position = GeopositionField()
class ChangePictureForm(forms.Form):

    profile_image = forms.FileField()
    # Add some custom validation to image field
    def clean_photo(self):
        photo = self.cleaned_data.get(['profile_picture'])
        if photo:
            format = Image.open(photo.file).format
            photo.file.seek(0)
            if format in VALID_IMAGE_FILETYPES:
                return photo
        raise forms.ValidationError('Yalnız jpg, png və tiff formatında şəkillər qəbul olunur')

doctor/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, TemplateView, FormView, DetailView, ListView
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template, render_to_string
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _
from geoposition import Geoposition

from doctor.models import BaseContact, ContactMessages, BaseSlider, DoctorBlog, BlogTv, \
    Xestelik, Country, Doctor, DoctorXestelik, DoctorCountry, DoctorTimeTable, \
    SponsorModel, MeetingModels, BlogComment, Banner, StaticPage
from doctor.forms import LeaveMessageForm, ChangePictureForm, \
    DashboardPersonalForm, BlogAddForm, PositionForm
from doctor.options.decorators import LoginRestrictedMixin
from doctor.tasks import MeetingRequestToDoctor, ReviewMessages ,MeetingResponseToPasient

from datetime import datetime
from threading import Thread

User = get_user_model()

class TezsagalGeneralView(View):
    def get_context_data(self, **kwargs):
        context = super(TezsagalGeneralView, self).get_context_data(**kwargs)
        context['static_pages'] = StaticPage.objects.all()
        return context


# Create your views here.
class TezsagalBaseView(View):
    def get_nav_menu_contacts(self):
        obj = BaseContact.objects.all().last()
        return obj

    def get_context_data(self, **kwargs):
        context = super(TezsagalBaseView, self).get_context_data(**kwargs)
        context['base_menu_contact'] = self.get_nav_menu_contacts()
        context['static_pages'] = StaticPage.objects.all()
        return context


class BaseIndexView(TezsagalBaseView, TemplateView):
    template_name = 'production/main_index/home.html'

    def get_slider(self):
        obj = BaseSlider.objects.filter(status=True)
        return obj

    def get_context_data(self, **kwargs):
        context = super(BaseIndexView, self).get_context_data(**kwargs)
        context['slider'] = self.get_slider()
        doc_ils = DoctorXestelik.objects.all()
        doc_ils_list = [int(x.xestelik.id) for x in doc_ils]
        context['ill'] = Xestelik.objects.filter(id__in=doc_ils_list)
        context['country'] = Country.objects.all()
        return context


class DashboardView(LoginRestrictedMixin,
                    TezsagalBaseView,
                    TemplateView):
    template_name = 'production/dashboard/dashboard_base.html'
    my_form = DashboardPersonalForm
    success_url = ''

    def post(self, request, *args, **kwargs):
        doctors = get_object_or_404(Doctor,user=request.user)
        xestelikler = request.POST.getlist('ilness')
        sheherler = request.POST.getlist('area')
        if xestelikler:
            for id in xestelikler:
                try:
                    DoctorXestelik.objects.get(xestelik_id=id, doctor=doctors)
                    pass
                except:
                    xes = DoctorXestelik(
                        xestelik_id=id,
                        doctor=doctors
                    )
                    xes.save()
        if sheherler:
            for y in sheherler:
                try:
                    DoctorCountry.objects.get(country_id=y, doctor=doctors)
                    pass
                except:
                    sheh = DoctorCountry(
                        country_id=y,
                        doctor=doctors
                    )
                    sheh.save()
        if not doctors.step_1:
            doctors.phone = request.POST.get('phone', '')
            doctors.prize_type = request.POST.get('prize_type', '')
            doctors.facebook_link = request.POST.get('facebook_link', '')
            doctors.twitter_link = request.POST.get('twitter_link', '')
            doctors.instagram_link = request.POST.get('instagram_link', '')
            doctors.base_name = request.POST.get('base_name', '')
            doctors.language = request.POST.get('language', '')
            if request.POST.get('qebul_qiymeti'):
                doctors.qebul_qiymeti = request.POST.get('qebul_qiymeti')
            else:
                doctors.qebul_qiymeti = 0
            doctors.pasient_types_az = request.POST.get('pasient_types_az', '')
            doctors.pasient_types_ru = request.POST.get('pasient_types_ru', '')
            doctors.pasient_types_ka = request.POST.get('pasient_types_ka', '')
            doctors.description_az = request.POST.get('personal_info_az', '')
            doctors.description_ru = request.POST.get('personal_info_ru', '')
            doctors.description_ka = request.POST.get('personal_info_ka', '')
            position_lat = request.POST.get('position_0')
            position_lon = request.POST.get('position_1')
            if position_lat:
                latitude = position_lat
            else:
                latitude = 0
            if position_lon:
                longitude = position_lon
            else:
                longitude = 0
            doctors.position = Geoposition(latitude, longitude)
            doctors.step_1 = True
            doctors.save()
            return redirect(reverse('base:dashboard-education'))
        else:
            doctors.phone = request.POST.get('phone', '')
            doctors.facebook_link = request.POST.get('facebook_link', '')
            doctors.prize_type = request.POST.get('prize_type', '')
            doctors.twitter_link = request.POST.get('twitter_link', '')
            doctors.instagram_link = request.POST.get('instagram_link', '')
            doctors.base_name = request.POST.get('base_name', '')
            doctors.language = request.POST.get('language', '')
            if request.POST.get('qebul_qiymeti'):
                doctors.qebul_qiymeti = request.POST.get('qebul_qiymeti')
            else:
                doctors.qebul_qiymeti = 0
            doctors.pasient_types_az = request.POST.get('pasient_types_az', '')
            doctors.pasient_types_ru = request.POST.get('pasient_types_ru', '')
            doctors.pasient_types_ka = request.POST.get('pasient_types_ka', '')
            doctors.description_az = request.POST.get('personal_info_az', '')
            doctors.description_ru = request.POST.get('personal_info_ru', '')
            doctors.description_ka = request.POST.get('personal_info_ka', '')
            position_lat = request.POST.get('position_0')
            position_lon = request.POST.get('position_1')
            if position_lat:
                latitude = position_lat
            else:
                latitude = 0
            if position_lon:
                longitude = position_lon
            else:
                longitude = 0
            # latitude = 0

            # return HttpResponse(businnes_type)
            # i = 1
            # for pos in position_get:
            #     if i == 1:
            #         latitude = Decimal(pos)
            #     if i == 2:
            #         longitude = Decimal(pos)
            #     i += 1
            doctors.position = Geoposition(latitude, longitude)
            doctors.save()
            return redirect(reverse('base:dashboard-education'))

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        doctor = get_object_or_404(Doctor,user=self.request.user)

        context['ill'] = Xestelik.objects.all()
        context['country'] = Country.objects.all()
        context['doctor'] = doctor
        try:
            context['positionform'] = PositionForm(initial={
                'position': Geoposition(doctor.position.latitude, doctor.position.longitude)
            })
        except:
            context['positionform'] = PositionForm()
        return context


# # Check user online or not
# class AjaxRequestTestingView(View):
#
#     def post(self,request,*args,**kwargs):
#         if request.is_ajax():
#             data = request.POST
#             return JsonResponse({"online":"true"})
#
#     @method_decorator(csrf_exempt)
#     def dispatch(self, request, *args, **kwargs):
#         return super(AjaxRequestTestingView, self).dispatch(request, *args, **kwargs)

# Just a testing case
# class TestingView(View):
#     http_method_names = ['get', 'post']
#     template_name = 'development/base/index.html'
#
#     def get(self, request, *args, **kwargs):
#         print([m.upper() for m in self.http_method_names if hasattr(self, m)])
#         response = render(request, self.template_name, {})
#         response.cookies['munis'] = True
#         response._headers['Developer'] = ('Developer','Munis Isazade')
#         return render(request, self.template_name, {})


#####################################################################
################## Latest Footer Contact Form #######################
#####################################################################

class LeaveMessageView(TezsagalBaseView,
                       FormView):
    model = ContactMessages
    form_class = LeaveMessageForm


class Test(TezsagalBaseView, TemplateView):
    template_name = 'development/testing/index.html'


class PersonalInfoDoctorView(TezsagalBaseView,
                             FormView):
    template_name = 'production/base'


class DoctorFormsView(ListView):
    model = DoctorBlog
    queryset = DoctorBlog.objects.filter(status=True)
    template_name = 'production/forms/index.html'

    def get_nav_menu_contacts(self):
        obj = BaseContact.objects.all().last()
        return obj

    def get_context_data(self, **kwargs):
        context = super(DoctorFormsView, self).get_context_data(**kwargs)

doctor/templates/production/blog/index.html
{% extends 'production/base/base_index.html' %}
{% load i18n %}

{% block facebook %}
     <meta property="og:url" content="https://{{ request.get_host }}{{ request.path }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="{{ object.title }}" />
    <meta property="og:description" content="{{ object.text|striptags|safe }}" />
    <meta property="og:image" content="https://{{ request.get_host }}/media/{{ object.image }}" />
{% endblock %}
 {% block content %}
     <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=640814552760977";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!--Page Title-->
        {% comment %}<section class="page-title">
        	<div class="container">
            	<div class="row clearfix">
                    <div class="col-md-6 col-sm-6 col-xs-12 pull-left">
						<h1>{% trans 'Blog' %} </h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
					</div>

					<div class="overlay"></div>
                </div>
            </div>
        </section>{% endcomment %}
        <!--Page Title Ends-->

		 <!--Sidebar Page-->
		<div class="sidebar-page">
			<div class="container">
				<div class="row clearfix">
					<!--Content Side-->
					<div class="col-md-8 col-sm-12 col-xs-12">
						<section class="blog-container">
							<!--Blog Post-->
							<article class="blog-post style-two">
								<div class="post-inner">
									<div class="image-box">
										<figure><a href="#"><img src="/media/{{ object.image }}" alt=""></a></figure>
										<div class="date">
											<h5>{{ object.date|date:'d' }}</h5>
											<p>{{ object.date|date:'M' }}</p>
										</div>
									</div>
									<div class="post-header">
										<h2><a href="">{{ object.title }}</a></h2>
										<ul class="post-info">
											<li><span class="flaticon-black"></span>&ensp; {{ object.author.user.get_full_name }}</li>
											<li><span class="flaticon-comments"></span>&ensp; 0  </li>

										</ul>
									</div>
									<div class="post-desc">
                                        {% autoescape off %}
										    {{ object.text }}
                                        {% endautoescape %}

									</div>





								</div>
							</article>
							<!--Comments Area-->


							<div class="leave-comment">
								<div class="section-title">
									<h3>{% trans 'Rəy yaz' %}</h3>
								</div>

                            <div class="fb-comments " width="100%"
                                 data-href="https://{{ request.META.HTTP_HOST }}{% url 'base:doctor-blog' object.slug %}"></div>
							</div>
						</section>
					</div>
					<!--Content Side-->

					<!--Sidebar-->
					<div class="col-md-4 col-sm-6 col-xs-12">
						{% comment %}<aside class="sidebar">

							<div class="sidebar_search">
								<form action="#">
									<input type="text" placeholder="Search....">
									<button class="tran3s color1_bg"><i class="fa fa-search" aria-hidden="true"></i></button>
								</form>
							</div> <!-- End of .sidebar_styleOne -->

							<!-- Popular Categories -->
							<div class="widget popular-categories wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
								<div class="sidebar-title"><h3>Categories</h3></div>

								<ul class="list">
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>Ambulance (6)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>Brain (9)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>Cardinal (3)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>Disease (5)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>Illness (7)</a></li>
								</ul>

							</div>

							<div class="sidebar_tags wow fadeInUp animated" data-wow-duration="1500ms" style="visibility: visible; animation-name: fadeInUp;">
								<div class="sidebar-title">
									<h3>Popular Tags</h3>
								</div>

								<ul>
									<li><a href="#" class="tran3s">Amazing</a></li>
									<li><a href="#" class="tran3s">Clean</a></li>
									<li><a href="#" class="tran3s">Mobile</a></li>
									<li><a href="#" class="tran3s">Flat</a></li>
									<li><a href="#" class="tran3s">Design</a>  </li>
									<li><a href="#" class="tran3s">Ios</a></li>
									<li><a href="#" class="tran3s">Themes</a> </li>
									<li><a href="#" class="tran3s">Clean</a> </li>

								</ul>
							</div> <!-- End of .sidebar_tags -->

							<div class="widget popular-categories wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
								<div class="sidebar-title"><h3>Archives</h3></div>

								<ul class="list">
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>February 2016 (6)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>September 2016 (9)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>July 2016 (3)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>Augest 2016 (5)</a></li>
									<li><a href="#"><span class="icon-left fa fa-chevron-right"></span>October 2016 (7)</a></li>
								</ul>

							</div>

							<div class="call wow fadeInUp" data-wow-duration="1500ms" style="background-image:url(images/resources/call.jpg);">

								<div class="content-box">
									<div class="overlay">
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco</p>
										<h2><span class="fa fa-call"></span>Call:  123 4561 5523</h2>
									</div>

								</div>

							</div>
						</aside>{% endcomment %}
					</div>
					<!--Sidebar-->
				</div>
			</div>
		</div>

{% endblock %}